### ISSUE TITLE
Tables dont recognize recipes with rf nbt data

### ISSUE THREAD

**Issue by Boolyman** [codetaylor/artisan-worktables#201]
#### Issue Description

Im not sure if its a crafttweaker issue or an Artisan issue... but Ive used CraftTweajer for years and never had this problem.  Custom recipes that include a Thermal Foundation rf capable item, such as a Fluxsaw or Capacitor, arent recognized as compatible item unless they get a bit of RF in them.  Despite the recipe not specifying any required nbt data on the item... which should allow for ANY nbt.

#### What Happens

Custom recipes that include a Thermal Foundation rf capable item, such as a Fluxsaw or Capacitor, arent recognized as compatible item unless they get a bit of RF in them.  Despite the recipe not specifying any required nbt data on the item... which should allow for ANY nbt.

#### What You Expect to Happen

The recipe to work

#### Script

https://pastebin.com/CAjM40uj

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2847
* CraftTweaker: 4.1.19
* Artisan Worktables:  1.22.9.
* Athenaeum:  1.17.4.

**Comment by codetaylor** [comment]
@Boolyman Thanks for the report!

Which item is the RF item you're having trouble with in the recipe?

```java
RecipeBuilder.get("engineer")
  .setShaped([[<thermalfoundation:material:657>, null, null, null, null], 
  [null, <embers:winding_gears>, <ore:plateInvar>, <ore:plateInvar>, <ore:plateInvar>], 
  [null, <thermalfoundation:material:640>, <thermalinnovation:saw>, <thermalfoundation:material:515>, <ore:plateInvar>], 
  [null, <ore:stickIron>, <thermalfoundation:material:640>, <thermalfoundation:material:513>, <ore:plateInvar>], 
  [<ore:stickIron>, null, null, null, null]])
  .setFluid(<liquid:solder> * 1000)
  .addTool(<ore:artisansCutters>, 48)
  .addTool(<ore:artisansSolderer>, 48)
.addOutput(<thermalinnovation:saw:1>)
.create();
```

**Comment by Boolyman** [comment]
The output (saw:1) doesnt craft uinless the one used in the recipe has a bit of rf in it.

**Comment by Boolyman** [comment]
Here is another streamer having issues crafting the Reinforced Jetpack, which uses the lower tier jetpack in the recipe.   The jetpack even appears in the output slot briefly... but wont craft.

https://www.youtube.com/watch?v=DXJQOyBmALc&feature=youtu.be

**Comment by codetaylor** [comment]
I haven't been able to reproduce the problem yet, but I did find some undesired behavior. Attempt 1 worked fine, but Attempt 2 uncovered some weird behavior. I will pursue this and see what it reveals.

---

### Attempt 1

Used this command to get saw with zero RF:

```
/give @p thermalinnovation:saw 1 0 {Energy: 0, Mode: 1}
```

Gives this item:

```java
<thermalinnovation:saw>.withTag({Energy: 0, Mode: 1})
```

With this script:

```java
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("engineer")
  .setShaped([
    [<thermalinnovation:saw>]
  ])
.addOutput(<thermalinnovation:saw:1>)
.create();
```

Seems to work fine:

![image](https://user-images.githubusercontent.com/1240716/67117353-5599a880-f197-11e9-9bf4-78084c4b1be1.png)

---

### Attempt 2

Using the same item as Attempt 1.

Add fluid requirement. With this script:

```java
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("engineer")
  .setShaped([
    [<thermalinnovation:saw>]
  ])
.addOutput(<thermalinnovation:saw:1>)
.setFluid(<liquid:water> * 1000)
.create();
```

Outputs the wrong item and shouldn't allow crafting at all due to the missing liquid.

![image](https://user-images.githubusercontent.com/1240716/67117516-be812080-f197-11e9-9088-cdf2e19e71ac.png)

**Comment by codetaylor** [comment]
Disregard Attempt 2 - I forgot about the vanilla recipes.

![image](https://user-images.githubusercontent.com/1240716/67118844-a8c12a80-f19a-11e9-82c2-dd67d2e1b77f.png)

**Comment by codetaylor** [comment]
### Attempt 3

With this script:

```java
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("engineer")
  .setShaped([
    [<thermalinnovation:saw>]
  ])
  .addOutput(<thermalinnovation:saw:1>)
  .setFluid(<liquid:water> * 1000)
.create();
```

Seems to work fine:

![image](https://user-images.githubusercontent.com/1240716/67118978-f473d400-f19a-11e9-9c2f-ba33a10ab962.png)

---

### Attempt 4

With this script:

```java
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("engineer")
  .setShaped([
    [<thermalinnovation:saw>]
  ])
  .addOutput(<thermalinnovation:saw:1>)
  .setFluid(<liquid:water> * 1000)
  .addTool(<ore:artisansCutters>, 48)
  .addTool(<ore:artisansSolderer>, 48)
.create();
```

Seems to work fine:

![image](https://user-images.githubusercontent.com/1240716/67119370-d8bcfd80-f19b-11e9-9ff9-9f645b76eb33.png)

---

### Attempt 5

With this script:

```java
import mods.artisanworktables.builder.RecipeBuilder;

// replace <embers:winding_gears> with <minecraft:dirt>
// replace <ore:stickIron> with <ore:ingotIron>

RecipeBuilder.get("engineer")
  .setShaped([
       [<thermalfoundation:material:657>, null, null, null, null],
       [null, <minecraft:dirt>, <ore:plateInvar>, <ore:plateInvar>, <ore:plateInvar>],
       [null, <thermalfoundation:material:640>, <thermalinnovation:saw>, <thermalfoundation:material:515>, <ore:plateInvar>],
       [null, <ore:ingotIron>, <thermalfoundation:material:640>, <thermalfoundation:material:513>, <ore:plateInvar>],
       [<ore:ingotIron>, null, null, null, null]])
  .addOutput(<thermalinnovation:saw:1>)
  .setFluid(<liquid:water> * 1000)
  .addTool(<ore:artisansCutters>, 48)
  .addTool(<ore:artisansSolderer>, 48)
.create();
```

Seems to work fine:

![image](https://user-images.githubusercontent.com/1240716/67120088-6816e080-f19d-11e9-8353-796072221bfb.png)

**Comment by codetaylor** [comment]
I have noticed the output item slot flickers and I'm going to dig into that next.

**Comment by codetaylor** [comment]
@Boolyman

I believe I've solved the output item flicker, but I don't think it has anything to do with your problem.

Can you please try the build below and report back? Thanks :)

[artisanworktables-1.12.2-1.22.9-TESTFIX.jar.zip](https://github.com/codetaylor/artisan-worktables/files/3745474/artisanworktables-1.12.2-1.22.9-TESTFIX.jar.zip)

**Comment by codetaylor** [comment]
Also, if there are any errors in the log when this happens, please provide them.

**Comment by VariableVixen** [comment]
Question: when crafting an RF-based item (not through a CT/AW recipe, just the built in Thermal \* mod's recipe) _does_ it have a tag for energy? Because if not, the issue might be to do with the energy tag not just being being `0` but not even _existing_ until it gets power. OP, try charging it up a tiny bit and then completely discharging it, in an enervation dynamo?

**Comment by Boolyman** [comment]
@PrincessRTFM If a recipe ingredient has no nbt data, according to CT wiki, it should accept any nbt data... so there is an issue either way.

@codetaylor Ill look into that build, but like you said, it can be hard to duplicate.  I have experienced it first hand, and am getting a lot of reports about it though.

**Comment by VariableVixen** [comment]
I know it's an issue regardless, but it might help narrow down _where_ the bug is coming from.

**Comment by codetaylor** [comment]
@Boolyman If you can reproduce this, please link your log.

**Comment by codetaylor** [comment]
This is the environment I've been testing in:

```
| ID                | Version       |
|:----------------- |:------------- |
| minecraft         | 1.12.2        |
| mcp               | 9.42          |
| FML               | 8.0.99.99     |
| forge             | 14.23.5.2847  |
| crafttweaker      | 4.1.19        |
| jei               | 4.15.0.291    |
| athenaeum         | 1.12.2-1.17.4 |
| artisanworktables | 1.12.2-1.22.9 |
| redstoneflux      | 2.1.0         |
| cofhcore          | 4.6.3         |
| cofhworld         | 1.3.1         |
| ctgui             | 1.0.0         |
| crafttweakerjei   | 2.0.3         |
| thermalfoundation | 2.6.3         |
| thermalinnovation | 0.3.3         |
```

**Comment by codetaylor** [comment]
### Attempt 6

Attempt to reproduce in the pack:
https://www.curseforge.com/minecraft/modpacks/seablock-rustic-waters

Seems to work fine:

![image](https://user-images.githubusercontent.com/1240716/67149772-4d5b6f00-f264-11e9-9b6e-38b5d6014c86.png)

I can't reproduce this.

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/67307991-41fb8400-f4ae-11e9-85ce-8526ec2ac77d.png)

@Boolyman Did you try the build I linked above? If so, what was the outcome?

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/67311148-e207dc00-f4b3-11e9-95ea-cfb5d8adb1a3.png)

@Boolyman I tried the recipe you suggested and it seems to work fine for me.

If this recipe is having the same problem, that indicates that it isn't related to NBT matching. It's most likely being caused by changes that were introduced to the output slot to accommodate for the creative mode feature.

The best that I can do with the current information is make some educated guesses and send you test builds.

Can you reliably reproduce the problem?

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/67590032-c9473280-f70e-11e9-923d-b9b565e036dc.png)

**Comment by codetaylor** [comment]
@Boolyman I hand crafted all the items for the recipe and it still works fine.

![image](https://user-images.githubusercontent.com/1240716/67622738-eee94000-f7d1-11e9-8cbc-6f49e7c907fa.png)

**Comment by codetaylor** [comment]
@Boolyman If I send you a new test build, will you test it and report back?

**Comment by Boolyman** [comment]
But you can clearly see that it does not work fine in my picture.  I can send you pics from others as well if you need.,  Are you testing it in some custom environment other than my pack?  If so, im not sure that will get us anywhere.  Yea, if I need to test something go ahead and send it to me.

**Comment by codetaylor** [comment]
> But you can clearly see that it does not work fine in my picture.

Yes, of course. I acknowledge that you are experiencing a problem. Just because I can't reproduce it doesn't mean that it's not happening. It just means that I have no way to debug the problem.

> I can send you pics from others as well if you need.

Piling on more images of it happening is not going to add any value to this debugging process.

> Are you testing it in some custom environment other than my pack?

I am testing in a minimal development environment, a minimal non-development environment, and your pack.

> Yea, if I need to test something go ahead and send it to me.

Great! Since I can't reproduce the problem the only way I have to debug this is if I send you builds to test and you give me feedback.

Is there any information in the logs regarding this issue?

**Comment by codetaylor** [comment]
Thank you for your help in getting to the bottom of this!

Can you reproduce the problem when using this older build?
[artisanworktables-1.12.2-1.21.7.jar.zip](https://github.com/codetaylor/artisan-worktables/files/3775236/artisanworktables-1.12.2-1.21.7.jar.zip)

**Comment by Boolyman** [comment]
No it does not work initially... however, I discovered that if you leave the recipe components in the table... exit the pack completely... then reload it, and look in the table, it works.  Dunno if that means there is a script loading problem...

It wont work to just log out and back in... you have to completely reload the pack.

**Comment by codetaylor** [comment]
Thank you for testing the older version. 

If the older version, `1.21.7`, has the same problem... then that doesn't rule out anything, unfortunately. If the problem disappeared in that version, then it would support the theory I had about where the problem was. But, since it didn't, I can return to pulling my hair out.

If a script was failing, I would expect there to be info in the `crafttweaker.log` or `latest.log`. The exit and reload behavior that you describe would align with what I thought could be causing the problem, but if the problem still occurs when switching to the older version, `1.21.7`, then we're back at square one.

I want to know if this problem is occurring in other packs, or if it's exclusive to your pack.

Here are some things we can try:

* Update to `1.22.10` and see if the problem still occurs
* Reproduce the problem, then send me your logs: `crafttweaker.log` and `latest.log`

**Comment by Boolyman** [comment]
Recipe not working:
[latest.log](https://github.com/codetaylor/artisan-worktables/files/3796386/latest.log)

After reloading with the items in the table and it works:
[latest2.log](https://github.com/codetaylor/artisan-worktables/files/3796396/latest2.log)

**Comment by codetaylor** [comment]
Thanks for the logs. Unfortunately I wasn't able to learn anything from the logs.

I do have a new build though. Please try to reproduce the problem using this build:
[artisanworktables-1.12.2-1.22.12-1-g25114c5.jar.zip](https://github.com/codetaylor/artisan-worktables/files/3801190/artisanworktables-1.12.2-1.22.12-1-g25114c5.jar.zip)

**Comment by Boolyman** [comment]
Nope, still not working.  This is increasingly frustrating.  You seem to be the only person who can't reproduce this issue.  I get a half dozen people a day coming into discord reporting this issue.  Im too embarrassed to even put out any patch updates for the pack with this issue unresolved, so its really put a damper on my release.  I do appreciate you looking into it... Im just expressing how untimely this is.

**Comment by codetaylor** [comment]
I agree, this is very frustrating for me as well. People are currently having a negative experience with my creation, hurting my brand, and I am ill equipped to solve the problem quickly.

With each build you help me test, we eliminate more and more possible causes, and hopefully get closer to an answer.

Let's rule out the tool matching changes next.

---

### Are you able to reproduce the problem using version `1.22.5`?

Here is the link: https://www.curseforge.com/minecraft/mc-mods/artisan-worktables/files/2799868

**Comment by codetaylor** [comment]
Please also try testing `1.22.13`. 

I fixed multiple, significant problems with the tool matching code in `1.22.13` in relation to #210 and the changes in tool matching introduced in `1.22.7`.

---

### Are you able to reproduce the problem using version `1.22.13`?

Here is the link: https://www.curseforge.com/minecraft/mc-mods/artisan-worktables/files/2821682

**Comment by Boolyman** [comment]
Still not working, here is a gif using latest update

![table](https://user-images.githubusercontent.com/24765883/68094874-450d5180-fe6a-11e9-9a8a-2083307e6b73.gif)

**Comment by codetaylor** [comment]
What was the result with `1.22.5`?

**Comment by Boolyman** [comment]
The same.  Are you unable to reproduce the issue even IN my pack?  Or you just cant reproduce it in your own testing environment?

**Comment by codetaylor** [comment]
I'm still unable to reproduce any of the problems you and others have expressed regarding this issue and I still don't know what the solution is.

Like you did with the `latest.log`, please provide two `crafttweaker.log` files, one when the problem occurs and another when the problem goes away.

**Comment by codetaylor** [comment]
>  Are you unable to reproduce the issue even IN my pack? Or you just cant reproduce it in your own testing environment?

As I already explained to you before, yes, I am testing in your pack. In fact, I have not been able to reproduce it **IN** your pack on two different computers after many, many attempts using the recipes you provided as well as others. I have spent many hours both in trying to reproduce this issue and trying to solve it.

Why don't you watch this video demonstrating that I can't reproduce the problem **IN** your pack since you don't seem to believe that I can't reproduce it: https://streamable.com/ql67v

**Comment by Boolyman** [comment]
You seem to be getting a bit snarky.  Neither of us are obligated to fix this issue, I know we don't get paid for this.  But I have a pack I would like to work smoothly, and you have a mod I'm sure you would like to have work properly.  So please, be patient if I need to reask a question or two after downloading and troubleshooting a half dozen mod revisions over the course of the last few weeks.

**Comment by Boolyman** [comment]
Log from recipe not working
[crafttweaker.log](https://github.com/codetaylor/artisan-worktables/files/3810739/crafttweaker.log)

Log after leaving items in table and relogging.
[crafttweaker.log](https://github.com/codetaylor/artisan-worktables/files/3810760/crafttweaker.log)

**Comment by codetaylor** [comment]
> You seem to be getting a bit snarky.

Absolutely I am, yes. I'm very frustrated and, in retrospect, I probably should have been more direct with you about what is frustrating me.

I am doing my best to solve a problem -- a problem that I don't have -- with my hands tied behind my back, a blindfold, and a severe deficit of actionable information.

I feel bad that I can't solve it and I feel a considerable amount of pressure to solve it because of [the things you said to me here](https://github.com/codetaylor/artisan-worktables/issues/201#issuecomment-549107989).

I feel frustrated when I ask for more information and I only receive part of the information I asked for. That information is the only thing that I have to work with to try and gain any insight into this issue. I understand you're busy with many different things, so am I, but please, if you don't have the time to provide all of the information I ask for, don't come in here and pile on about how frustrated you are because it hasn't been fixed yet. #feelsbadman

It felt pretty terrible when I went into your Discord to search for more information and I saw this:
![image](https://user-images.githubusercontent.com/1240716/68237051-4bf7a980-ffbb-11e9-814d-8dc7c1a69107.png)

It makes me think you don't believe me and are trying to belittle my efforts for some reason and that hurts because I have spent a considerable amount of my time trying to help you with this.

I need you to understand that:
  
  * if there is a solution, you are a big part of it; the onus is not mine alone -- it is *ours* and I need your active involvement in the process to solve this.
  * this absolutely *will not* get solved without active, outside involvement by you or others with the same issue.
  * this process will likely take considerably longer than either of us want it to, but if you provide me with all of the information that I ask for, we can get through it.

Thank you for providing the `crafttweaker.log` files. I was really hoping that the logs would reveal more information about why this problem is occurring, but they haven't given me any new insight.

My next plan of action regarding this issue is to spend the time to make a special build of the mod that will log a lot of extra information to a separate log file. When it is complete, I will ask you to reproduce the problem using the special build and send me the logs. I will then analyze the logs for any indicators that might shed some light on why this is happening.

Thank you very much for the tests you have performed and the information you have provided at my request. I ask that you please have patience and plan accordingly as this could take some time to resolve.

**Comment by Boolyman** [comment]
> Absolutely I am, yes. 

Well don't.  

> I have spent a considerable amount of my time trying to help you with this.

Trying to figure out why your mod is not working properly?   I wouldn't really label that as "trying to help me".  If anything, it's of mutual benefit.  But don't go out of your way any more, I will just reconfigure the recipes in question over to use Extended Crafting tables instead.  

Thanks for your help.

**Comment by Xorbah** [comment]
Lmao, this was an absolute dumpster fire of rudeness.

**Comment by codetaylor** [comment]
Should be fixed in `1.22.16`
